changed Dockerfile to use VIVO-1.11.0 release
vivo-community/vivo-docker2 pull request #11
Opened 2019-11-14 20:31 UTC by ht29

changed Dockerfile to use VIVO-1.11.0 release and also remove extra vivo folder and everything is part of VIVO folder

2019-11-20 20:44 UTC, awoods requested changes

2019-11-20 20:44 UTC, awoods commented on vivo/Dockerfile
> +#RUN git clone https://github.com/vivo-project/Vitro.git Vitro -b rel-1.11.0-RC
Please remove unused, commented out commands.

2019-11-20 20:44 UTC, awoods commented on vivo/Dockerfile
> +#COPY ./dockercompose.runtime.properties /usr/local/vivo/home/config/runtime.properties
Please remove unused, commented out commands.

2019-11-27 01:01 UTC, qjhart reviewed
Builds and runs for me.  I'm fine with not checking the MD5 sum, and I actually kind of like the development  clue for using #RUN git clone as alternative method.

2019-11-27 13:57 UTC, awoods commented
Thanks for the feedback, @qjhart . I will go ahead and merge.

2019-11-27 13:57 UTC, awoods approved these changes

2019-11-27 13:58 UTC, merged