Updates to docker files
vivo-community/vivo-docker2 pull request #6
Opened 2019-07-24 00:15 UTC by roflinn

Updates to docker to use current versions of Maria DB and Solr.
This will also git/github to pull the code for the maven build.

These were tested by Ralph, Don, and Andrew.

2019-08-06 19:57 UTC, delsborg commented on vivo/Dockerfile
>  RUN apt-get install -y maven git
Previously we worked on a multistage build where the war was built in one image and then copied to a tomcat image. This version does both in the same image.
Wouldn't it be best to decouple the build from the tomcat image?
I still do prefer this change over the previous version that downloaded a VIVO .tgz file

2019-08-06 20:27 UTC, roflinn commented on vivo/Dockerfile
>  RUN apt-get install -y maven git
long term 100% agree, but may have a seperate image.  I'm thinking about the docker for someone who is quick testing/demoing vs ongoing dev.

2019-08-06 20:56 UTC, awoods approved these changes

2019-08-06 21:01 UTC, awoods requested changes
I spoke too soon. When hitting http://localhost:8080/vivo, I get:
```
java.sql.SQLException: Access denied for user 'vitrodbUsername'@'172.18.0.4' (using password: YES)
```

2019-08-19 21:00 UTC, roflinn commented
Closing - Please go to PR #7

2019-08-19 21:00 UTC, closed without merging